server:
  port: 7003

spring:
  application:
    # 服务提供者在注册中心的项目名
    name: zookeeper-provider-user
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true

# SpringBoot2.1之后，项目启动时，控制台不自动打印api了，需要做如下配置：更改 org.springframework.web 包的日志级别
logging:
  level:
    org.springframework.web: TRACE

# actuator监控端点
management:
  endpoints:
    web:
      # Web端点的基本路径,默认为/actuator
      base-path: /actuator
      # 默认值访问health,info端点  用*可以包含全部端点
      exposure:
        include: "*"
